blank_issues_enabled: false
contact_links:
  - name: SearX instances list has moved.
    url: https://github.com/searxng/searx-instances
    about: SearX instances list has moved to a new GitHub repository.